### ISSUE TITLE
Proxmox LXC: Container Create fails when using non-default 'disk'

### ISSUE THREAD

**Issue by Vacant0mens** [bellackn/ansible-collection-homelab#20]
**Describe the bug**
When running a play to create a container, or multiple containers, where the `disk` parameter/variable is specified, Proxmox throws this error message:
```
The file /dev/rbd-pve/<GUID>/rados/vm-<ID>-disk-0 does not exist and no size was specified.
Removing image <#>% complete...
TASK ERROR: unable to create CT <ID> - command 'mkfs.ext4 -O mmp -E 'root_owner=0:0' /dev/rbd-pve/<GUID>/rados/vm-<ID>-disk-0' failed: exit code 1
```
**To Reproduce**
1. run a play with config similar to this:
```yaml
    proxmox_lxc_api_host: <proxmoxHost>
    proxmox_lxc_api_user: <user>@pam
    proxmox_lxc_api_password: <proxmoxPassword>
    proxmox_lxc_validate_certs: false
    proxmox_lxc_storage: rados
    proxmox_lxc_password: <containerPassword>
    proxmox_lxc_ostemplate: cephfs:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst
    proxmox_lxc_timezone: <timezone>
    proxmox_lxc_containers_present:
      - vmid: <ID>
        node: <proxmoxNode>
        hostname: <containerHost>
        cores: 4
        memory: 8192
        disk: rados:8
        mounts:
          mp0: volume=/media/Media,mp=/media/Media
        netif: |
          {"net0":"name=eth0,gw=192.168.5.1,ip=dhcp,ip6=dhcp,bridge=vmbr0"}
        unprivileged: false
        startup:
          order: 2
        features:
          - mount=cifs;nfs
```

**Expected behavior**
A container should get created with an 8gb root disk.

**Desktop (please complete the following information): **
 - Running OS: Debian 12 (LXqt desktop)
 - Browser: Firefox
 - Proxmox Version: 8.4.1
 - Python Version: 3.11
 - Ansible Version: 2.14.18

**Additional context**
I don't know that this is necessarily relevant, but I'm running the task in a venv on the target machine, with:
```yaml
  vars:
    project_home: /opt/ansible
    ansible_python_interpreter: /opt/ansible/venv/bin/python
    pip_executable: /opt/ansible/venv/bin/pip
```
