### ISSUE TITLE
Ping outside check only works, when not using a fqdn as hostname 

### ISSUE THREAD

**Issue by deveth0** [bellackn/ansible-collection-homelab#4]
My setup:

- hostname: proxmox.foo.bar
- proxmox_lxc_node: proxmox
- proxmox_lxc_api_host: localhost

I run the ansible playbook on my proxmox machine, but this causes the `delegate_to` to fail cause it cannot delegate to the configured node. 

```
- name: Ping outside  # noqa 503
  command: "lxc-attach -n {{ proxmox_lxc_started.msg[3:6] }} -- ping {{ proxmox_lxc_ping_server }} -c 2"
  delegate_to: "{{ proxmox_lxc_node }}"
  when:
    - proxmox_lxc_created.changed
    - item.netif is defined or proxmox_lxc_netif | length > 0
```

**Comment by deveth0** [comment]
Example Playbook:

````

- name: Set up LXCs
  hosts: my-proxmox-server
  vars:
    docker_host: docker.foo.bar

    proxmox_lxc_containers_present:
      - hostname: "{{ docker_host }}"
        pasword: foobar
        ostemplate: local:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz
        cpus: 4
        cores: 4
        memory: 12288
        swap: 4096
        disk: 100
        netif: |
          {"net0":"name=eth0,gw=192.168.2.254,ip=192.168.2.19/24,bridge=vmbr1"}
        description: Created with Ansible
        unprivileged: true
        features:
          - "keyctl=1"
          - "nesting=1"

  roles:
    - bellackn.proxmox_lxc

  post_tasks:
    - name: "Add {{docker_host}} to group dockerservers"
      add_host:
        name:  "{{ docker_host }}"
        groups: dockerservers

- name: Install some other stuff on the new system
  hosts: dockerservers
  roles:
    - oefenweb.fail2ban

````

**Comment by bellackn** [comment]
Please try it like in the example below.
Changes:
* Use the `pubkey` variable to add an SSH key that Ansible can use to access the new host
* Specify the user that Ansible should use to connect with the container (`ansible_user`)
* Add the IP address to the host as `ansible_ssh_host` - not sure if this is necessary, but might be if your controlhost cannot resolve the hostname. However, it doesn't hurt specifying it I guess

```
- name: Set up LXCs
  hosts: proxmox
  vars:
    docker_host: docker.foo.bar
    docker_ip: 192.168.0.230

    proxmox_lxc_containers_present:
      - hostname: "{{ docker_host }}"
        password: foobar
        ostemplate: local:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz
        cpus: 1
        cores: 1
        memory: 4096
        swap: 2048
        disk: 50
        netif: |
          {"net0":"name=eth0,gw=192.168.0.1,ip={{ docker_ip }}/32,bridge=vmbr0"}
        pubkey: "{{ lookup('file', 'id_rsa.pub') }}"
        description: Created with Ansible
        unprivileged: true
        features:
          - "keyctl=1"
          - "nesting=1"

  roles:
    - bellackn.proxmox_lxc

  post_tasks:
    - name: "Add {{docker_host}} to group dockerservers"
      add_host:
        name: "{{ docker_host }}"
        ansible_ssh_host: "{{ docker_ip }}"
        ansible_user: root
        groups: dockerservers
      delegate_to: localhost

- name: Install some other stuff on the new system
  hosts: dockerservers
  tasks:
    - ping:

- name: Remove tmp host
  hosts: proxmox
  gather_facts: no
  vars:
    docker_host: docker.foo.bar
    proxmox_lxc_containers_absent:
      - hostname: "{{ docker_host }}"
  roles:
    - bellackn.proxmox_lxc
```

PS: Not sure if this is a problem with *all* container templates, but this Ubuntu one has the setting ` PermitRootLogin without-password` set in `/etc/ssh/sshd_config`, so you **must** use an SSH key to access the host with Ansible if you don't change this somehow beforehand!

**Comment by deveth0** [comment]
Oh sorry, I guess we're talking about differened problems. 
I DON'T have issues with the connection to the newly created host (in fact, I'm already using a pubkey, but this is set in my host_vars). 

I tried to get a bit more into the problem and it seems as if the issue is not caused by the local connection but by the FQDN I need to use.

The issue is that your role tries to delegate the ping command to  `proxmox_lxc_node` which in my case is `proxmox`. 

BUT: the actual FQDN I use is proxmox.foo.bar, so there is no configuration available for `proxmox` but only for `proxmox.foo.bar`. 

````yml
all:
  hosts:    
    proxmox.foo.bar:      
      ansible_connection: local
````

Workaround: add proxmox to hosts, just for this single use-case

I guess it won't hurt to add a variable `proxmox_lxc_host` that defaults to  proxmox_lxc_node` and is used for the delegate, wdyt?
